import React from 'react'

function MidSection() {
  return (
    <div className='mid-section'>MidSection
    <p>Sri Lanka: The Island of Serendipity

    se as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often rse as its landscapes. The island's history dates back over two millennia, making it one of the oldest continually inhabited places in the world. One of its earliest recorded civilizations, the Anuradhapura Kingdom, emerged around the 4th century BCE, and its ancient city of Anuradhapura is now a UNESCO World Heritage Site, replete with ancient dagobas (stupas), monastic ruins, and sacred Bodhi trees.
 Perahera, often r
Culinary Delights</p>
    </div>
  )
}

export default MidSection